/* __CREATE_MANAGER__ */

CREATE USER MANAGER1 IDENTIFIED BY MGR
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

GRANT cemetery_manager,CONNECT TO MANAGER1;

GRANT EXECUTE ON CEMETERY.RELIGIOUS_AREA_UTILS TO MANAGER1;
GRANT EXECUTE ON CEMETERY.SECTOR_UTILS TO MANAGER1;
GRANT EXECUTE ON CEMETERY.PAYMENT_UTILS TO MANAGER1;
GRANT EXECUTE ON CEMETERY.GRAVE_FOR_MANAGER TO MANAGER1;
GRANT EXECUTE ON CEMETERY.FUNERAL_FOR_MANAGER TO MANAGER1;
GRANT EXECUTE ON CEMETERY.SERVICE_WORKER_UTILS TO MANAGER1;
GRANT EXECUTE ON CEMETERY.BURIED_UTILS TO MANAGER1;



/* __CREATE_GUEST_USER__ */
CREATE USER GUEST1 IDENTIFIED BY 123
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
 
GRANT CONNECT TO GUEST1;

GRANT EXECUTE ON CEMETERY.GUEST_PACKAGE TO GUEST1;
